In [1]:
import pandas as pd
import os
import geopandas as gpd

In [3]:
DATA_DIR = ('../../../../data/GMW_extent_V4')

## Load locations

In [4]:
locations_combined = pd.read_csv('https://storage.googleapis.com/mangrove_atlas/widget_data/locations_merged.csv')
locations_combined.head()

,name,iso,wdpaid,type,location_idn,id
0,Baffle Creek,AUS,308657.0,wdpa,000bd204-c0fd-510b-a1ad-132a7ef7470d,1563
1,Mangrove,TZA,555623909.0,wdpa,00250a0f-f66d-54a0-b7a3-d80035881cbf,1564
2,Wuthathi Rev.1 (Margaret Bay),AUS,555543690.0,wdpa,0041637b-f6a2-5b89-87ce-850f5c5431b3,1565
3,Lignumvitae Key Aquatic Preserve,USA,555586771.0,wdpa,005b49ef-6b7f-575a-85b3-ff19261a0755,1566
4,Mu Ko Ang Thong MNP,THA,900849.0,wdpa,00921349-70fb-5a7e-8207-b3157aecc349,1567

In [4]:
locations_combined['type'].value_counts()

type
wdpa       3001
country     122
aoi           2
Name: count, dtype: int64

In [5]:
locations_country = locations_combined[locations_combined['type'] == 'country']
locations_wdpa = locations_combined[locations_combined['type'] == 'wdpa']
locations_wdpa['wdpaid'] = locations_wdpa['wdpaid'].astype(int)

## Extent data

### Countries

In [6]:
country_stats = pd.read_parquet(os.path.join(DATA_DIR,
                                             'gmw_mng_extent_stats_v4112_corrected',
                                             'gmw_v4_timeseries_4112_gmw_country_stats_corr_area.parquet'))
country_stats.reset_index(drop=False, inplace=True)
#Correct ISO codes
country_stats.loc[country_stats['cnty_name'] == 'Bonaire', 'iso'] = 'BES'
country_stats.loc[country_stats['cnty_name'] == 'Europa Island', 'iso'] = 'ATF'
print(len(country_stats))
country_stats.head(10)

129

,iso,cnty_name,1985,1986,1987,1988,1989,1990,1991,1992,...,2016,2017,2018,2019,2020,2021,2022,2023,2024,2025
0,ABW,Aruba,86.126026,86.211384,86.552848,86.552848,87.406216,88.259730,88.345088,88.430428,...,1.041343e+02,1.038778e+02,1.054994e+02,1.036219e+02,1.051582e+02,1.072066e+02,1.096816e+02,1.100230e+02,1.105351e+02,1.130099e+02
1,AGO,Angola,26456.909115,26446.147088,26486.295782,26526.447466,26142.066852,26244.761417,26264.271899,26260.902105,...,2.724583e+04,2.753727e+04,2.789533e+04,2.825260e+04,2.856683e+04,2.870418e+04,2.869819e+04,2.861731e+04,2.856278e+04,2.855748e+04
2,AIA,Anguilla,3.989323,3.989323,3.989323,3.989323,3.989323,3.989323,3.989323,3.989323,...,5.983995e+00,3.490664e+00,3.656845e+00,4.155384e+00,4.487828e+00,4.820277e+00,6.233158e+00,7.479845e+00,7.812289e+00,8.061440e+00
3,ARE,United Arab Emirates,1418.290615,1420.986591,1438.187756,1450.918395,1487.311874,1505.138359,1542.395562,1626.186527,...,5.997168e+03,6.807207e+03,7.030448e+03,7.576244e+03,7.922062e+03,8.285883e+03,8.794197e+03,9.382661e+03,9.615833e+03,9.658781e+03
4,ASM,American Samoa,27.452234,27.452234,27.452234,27.452234,27.452234,27.452234,27.452234,27.452234,...,3.287489e+01,3.270543e+01,3.279019e+01,3.321389e+01,3.304440e+01,3.329855e+01,3.363750e+01,3.338318e+01,3.372210e+01,3.346779e+01
5,ATF,Europa Island,626.890012,626.890012,626.890012,626.890012,626.890012,626.890012,626.890012,626.890012,...,6.343380e+02,6.329619e+02,6.346618e+02,6.395998e+02,6.407331e+02,6.433235e+02,6.461568e+02,6.509328e+02,6.543328e+02,6.644516e+02
6,ATF_GI,Glorioso Islands,0.428197,0.428197,0.428197,0.428197,0.428197,0.428197,0.428197,0.428197,...,4.281969e-01,4.281969e-01,4.281969e-01,4.281969e-01,4.281969e-01,4.281969e-01,4.281969e-01,4.281969e-01,4.281969e-01,4.281969e-01
7,ATG,Antigua and Barbuda,703.457094,703.457094,703.039024,702.621792,650.257407,650.841565,650.841325,651.091901,...,8.965062e+02,8.215627e+02,8.087364e+02,8.209913e+02,8.385668e+02,8.593066e+02,8.844658e+02,9.400836e+02,9.504961e+02,9.526774e+02
8,AUS,Australia,929445.666098,929725.232119,932088.746230,935416.968155,951616.723467,953616.635197,955458.091914,957243.774376,...,1.013203e+06,1.012548e+06,1.000950e+06,1.000969e+06,1.008293e+06,1.022815e+06,1.030540e+06,1.038490e+06,1.050207e+06,1.069096e+06
9,BEN,Benin,2074.118084,2075.768242,2083.237468,2087.666928,2174.866132,2256.853604,2259.719637,2257.027242,...,2.351522e+03,2.385394e+03,2.401809e+03,2.230885e+03,2.148898e+03,2.024526e+03,2.011498e+03,1.954089e+03,1.924039e+03,1.915702e+03

In [7]:
#Extent locations without match on locations
country_stats[~country_stats['iso'].isin(locations_country['iso'])]

,iso,cnty_name,1985,1986,1987,1988,1989,1990,1991,1992,...,2016,2017,2018,2019,2020,2021,2022,2023,2024,2025
6,ATF_GI,Glorioso Islands,0.428197,0.428197,0.428197,0.428197,0.428197,0.428197,0.428197,0.428197,...,0.428197,0.428197,0.428197,0.428197,0.428197,0.428197,0.428197,0.428197,0.428197,0.428197
14,BLM,Saint Barthélemy,1.498363,1.498363,1.498363,1.498363,1.165393,1.165393,1.165393,1.165393,...,1.748083,1.082147,0.998905,1.082146,1.498365,1.914585,2.663760,2.996730,3.163219,3.496200
20,CCK,Cocos (Keeling) Islands,0.684478,0.684478,0.684478,0.684478,0.684478,0.684478,0.684478,0.684478,...,4.615220,4.615220,5.128581,5.128581,5.727503,7.524261,7.780942,7.780942,7.866502,7.952066
64,KWT,Kuwait,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.382027,0.382027,0.382027,0.382027,0.382027,0.534870
74,MNP,Northern Mariana Islands,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.253150,0.337533,...,1.940807,2.109572,2.193955,1.940807,1.940807,2.025190,2.278338,2.362720,2.869017,3.206549
79,MUS_CA,Chagos Archipelago,3.132505,3.132505,3.132505,3.132505,3.132505,3.132505,3.132505,3.132505,...,3.567574,3.567574,3.306532,2.784448,2.784448,2.697434,2.523406,2.349378,2.349378,2.349378
85,NRU,Nauru,0.524193,0.524193,0.524193,0.524193,0.524193,0.524193,0.524193,0.524193,...,0.524193,0.611559,0.524193,0.611559,0.524193,0.524193,0.524193,0.524193,0.436828,0.524193

In [8]:
locations_country[~locations_country['iso'].isin(country_stats['iso'])]

Empty DataFrame
Columns: [name, iso, wdpaid, type, location_idn, id]
Index: []

In [9]:
country_stats_id = locations_country[['iso', 'id']].merge(country_stats, how='left', left_on='iso', right_on='iso')
country_stats_id.drop(columns=['iso', 'cnty_name'], inplace=True)
country_stats_long = country_stats_id.melt(id_vars=['id'], var_name='year', value_name='value')
country_stats_long['indicator'] = 'habitat_extent_area'
country_stats_long = country_stats_long[['id','indicator', 'year',  'value']]
country_stats_long.sort_values(by=['id', 'year'], inplace=True)
country_stats_long.dropna(inplace=True)

country_stats_long.head(10)

        id            indicator  year      value
0     1645  habitat_extent_area  1985  24.761074
122   1645  habitat_extent_area  1986  24.761074
244   1645  habitat_extent_area  1987  24.761074
366   1645  habitat_extent_area  1988  24.761074
488   1645  habitat_extent_area  1989  24.761074
610   1645  habitat_extent_area  1990  24.761074
732   1645  habitat_extent_area  1991  24.761074
854   1645  habitat_extent_area  1992  24.761074
976   1645  habitat_extent_area  1993  24.918304
1098  1645  habitat_extent_area  1994  42.434590

### WDPAs

In [6]:
wdpa_stats = pd.read_parquet(os.path.join(DATA_DIR,
                                         'gmw_v4112_stats_wdpa_wdoecms',
                                         'mng_ext_stats_v4112',
                                         'gmw_v4_timeseries_v4112_wdpa_jun2026_stats_corr_area.parquet'))
wdpa_layer = gpd.read_file(os.path.join(DATA_DIR,
                                        'gmw_v4112_stats_wdpa_wdoecms',
                                        'WDPA_poly_Jun2026_intersect_hab_mask_v29_uid_n_pxls_vld.gpkg'))
wdpa_layer = wdpa_layer[['SITE_ID']]

wdpa_stats['wdpaid'] = wdpa_layer['SITE_ID'].values # !! direct merge by order of rows in the geopackage and parquet file
wdpa_stats.head(3)

,name,1985,1986,1987,1988,1989,1990,1991,1992,1993,...,2017,2018,2019,2020,2021,2022,2023,2024,2025,wdpaid
UID,,,,,,,,,,,,,,,,,,,,,
1,Inagua National Park,351.488358,356.305602,362.185825,368.309369,388.395746,389.293826,389.375592,390.600688,397.866967,...,464.392686,496.967685,521.134445,534.361641,538.850617,544.320057,556.158150,568.649582,588.482592,24
3,Reserva Biológica Do Lago Piratuba,61904.409346,61893.057226,61897.774374,61938.297173,62093.145204,62158.212806,62122.150249,62181.029793,62467.783640,...,58098.269604,58134.431972,58074.516141,57794.000046,57244.409525,56315.982866,56124.202546,56182.976135,55982.886942,42
4,Reserva Biológica De Una,175.606961,175.522578,175.522576,175.860112,177.210267,178.307269,178.813580,179.066736,179.151122,...,180.332531,181.682711,182.189033,182.948507,183.370447,183.117288,182.948514,181.598338,183.707991,48

In [7]:
print("WDPA locations in database", len(locations_wdpa))
print("WDPA locations in stats", len(wdpa_stats))
print("Database locations without match on stats", len(locations_wdpa[~locations_wdpa['wdpaid'].isin(wdpa_stats['wdpaid'])]))

WDPA locations in database 3001
WDPA locations in stats 4013
Database locations without match on stats 156

In [11]:
wdpa_stats_id = locations_wdpa[['wdpaid', 'id']].merge(wdpa_stats, how='left', left_on='wdpaid', right_on='wdpaid')
wdpa_stats_id.drop(columns=['wdpaid', 'name'], inplace=True)

wdpa_stats_long = wdpa_stats_id.melt(id_vars=['id'], var_name='year', value_name='value')
wdpa_stats_long['indicator'] = 'habitat_extent_area'
wdpa_stats_long = wdpa_stats_long[['id','indicator', 'year',  'value']]
wdpa_stats_long.sort_values(by=['id', 'year'], inplace=True)
wdpa_stats_long.dropna(inplace=True)
wdpa_stats_long.head(10)

         id            indicator  year       value
0      1563  habitat_extent_area  1985  469.589555
3070   1563  habitat_extent_area  1986  469.589555
6140   1563  habitat_extent_area  1987  472.059425
9210   1563  habitat_extent_area  1988  475.325913
12280  1563  habitat_extent_area  1989  485.285069
15350  1563  habitat_extent_area  1990  489.826409
18420  1563  habitat_extent_area  1991  491.101150
21490  1563  habitat_extent_area  1992  492.057187
24560  1563  habitat_extent_area  1993  493.092909
27630  1563  habitat_extent_area  1994  495.323666

In [12]:
len(wdpa_stats_long), len(country_stats_long)

(119474, 5002)

In [13]:
extent_stats_long = pd.concat([country_stats_long, wdpa_stats_long], axis=0)
extent_stats_long.rename(columns={'id': 'location_id'}, inplace=True)
#convert values from ha to km2!
extent_stats_long['value'] = extent_stats_long['value'] * 0.01

extent_stats_long.to_csv(os.path.join('../../../../data', 'extent_stats_v4.csv'), index=False)
#extent_stats_long[0:3].to_csv(os.path.join('../../../../data', 'extent_stats_v4_TEST.csv'), index=False)